module.exports = {
    /**AUTH CODES */
    CODE_AUTH_LOGIN: 'AULO',
    /**USUARIO CODES */
    CODE_USER_CREATE: 'USCR',
    CODE_USER_UPDATE: 'USUP',
    CODE_USER_DELETE: 'USDL',
    /**PERSONA CODES */
    CODE_PERSON_CREATE: 'PECR',
    CODE_PERSON_UPDATE: 'PEUP',
    CODE_PERSON_DELETE: 'PEDL',
    /**EMPRESA CODES */
    CODE_COMPANY_CREATE: 'COCR',
    CODE_COMPANY_UPDATE: 'COUP',
    CODE_COMPANY_DELETE: 'CODL',
    /**CONSULTORA CODES */
    CODE_CONSULTANT_CREATE: 'CNCR',
    CODE_CONSULTANT_UPDATE: 'CNUP',
    CODE_CONSULTANT_DELETE: 'CNDL',
    /**INTERES CODES */
    CODE_INTEREST_CREATE: 'INCR',
    CODE_INTEREST_UPDATE: 'INUP',
    CODE_INTEREST_DELETE: 'INDL',
    /**UFV CODES */
    CODE_UFV_CREATE: 'UFCR',
    CODE_UFV_UPDATE: 'UFUP',
    CODE_UFV_DELETE: 'UFDL',
    /**CALENDARIO CODES */
    CODE_CALENDAR_CREATE: 'CLCR'
}